folder('DSL/PROD'){
    displayName('PROD')
    description('PROD')
}
folder('DSL/STAGE'){
    displayName('STAGE')
    description('STAGE')
}
folder('DSL/DEV'){
    displayName('DEV')
    description('DEV')
}