import javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration
import jenkins.model.GlobalConfiguration

GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).useScriptSecurity=false
GlobalConfiguration.all().get(GlobalJobDslSecurityConfiguration.class).save()

pipeline {
    agent any
    stages {
        stage('FolderDSL') {
            steps {
                jobDsl targets: 'foldersRoot.groovy',
                removedJobAction: 'DELETE',
                removedViewAction: 'DELETE',
                lookupStrategy: 'SEED_JOB'
            }
        }

        stage('FolderENV') {
            steps {
                jobDsl targets: 'foldersENV.groovy',
                removedJobAction: 'DELETE',
                removedViewAction: 'DELETE',
                lookupStrategy: 'SEED_JOB'
            }
        }

        stage('Pipeline') {
            steps {
                jobDsl targets: 'dsl.groovy',
                removedJobAction: 'DELETE',
                removedViewAction: 'DELETE',
                lookupStrategy: 'SEED_JOB'
            }
        }
    }
}